# Generated by Django 3.1.4 on 2021-01-01 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.IntegerField()),
                ('win_prize', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('per_kill', models.IntegerField()),
                ('spots', models.IntegerField()),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('room_pass', models.CharField(max_length=100)),
                ('game_id', models.IntegerField()),
            ],
        ),
    ]
