# Generated by Django 3.1.4 on 2021-01-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffWarAdminApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
