# Generated by Django 3.1.4 on 2021-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffWarAdminApi', '0002_auto_20210101_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('game_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
    ]
