# Generated by Django 3.1.4 on 2021-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffWarUserApi', '0006_auto_20210101_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingamemodel',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
