# Generated by Django 3.1.4 on 2021-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffWarUserApi', '0007_joingamemodel_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmodel',
            name='wth_status',
            field=models.BooleanField(default=False),
        ),
    ]
